package com.ecommerce.mapper;

import com.ecommerce.dto.ProductDTO;
import com.ecommerce.model.Product;
import org.springframework.stereotype.Component;

@Component
public class ProductMapper {

    public ProductDTO toDTO(Product product) {
        if (product == null) {
            return null;
        }
        ProductDTO dto = new ProductDTO();
        dto.setId(product.getId());
        dto.setName(product.getName());
        dto.setDescription(product.getDescription());
        dto.setPrice(product.getPrice());
        dto.setStock(product.getStock());
        dto.setImageUrl(product.getImageUrl());
        dto.setCategory(product.getCategory());
        dto.setBrand(product.getBrand());
        dto.setRating(product.getRating());
        dto.setNumReviews(product.getNumReviews());
        dto.setIsFeatured(product.isFeatured());
        dto.setIsActive(product.isActive());
        dto.setCreatedAt(product.getCreatedAt());
        return dto;
    }

    public Product toEntity(ProductDTO dto) {
        if (dto == null) {
            return null;
        }
        Product product = new Product();
        // ID is usually generated by DB, so we might not set it on creation
        product.setId(dto.getId());
        product.setName(dto.getName());
        product.setDescription(dto.getDescription());
        if (dto.getPrice() != null)
            product.setPrice(dto.getPrice());
        if (dto.getStock() != null)
            product.setStock(dto.getStock());
        product.setImageUrl(dto.getImageUrl());
        product.setCategory(dto.getCategory());
        product.setBrand(dto.getBrand());
        if (dto.getIsFeatured() != null)
            product.setFeatured(dto.getIsFeatured());
        if (dto.getIsActive() != null)
            product.setActive(dto.getIsActive());

        // Rating and reviews are usually not set by DTO on creation, but maybe update
        // Leaving out createdAt as it's set by constructor/Entity logic usually
        return product;
    }

    public void updateEntityFromDTO(Product product, ProductDTO dto) {
        if (dto.getName() != null)
            product.setName(dto.getName());
        if (dto.getDescription() != null)
            product.setDescription(dto.getDescription());
        if (dto.getPrice() != null)
            product.setPrice(dto.getPrice());
        if (dto.getStock() != null)
            product.setStock(dto.getStock());
        if (dto.getImageUrl() != null)
            product.setImageUrl(dto.getImageUrl());
        if (dto.getCategory() != null)
            product.setCategory(dto.getCategory());
        if (dto.getBrand() != null)
            product.setBrand(dto.getBrand());
        if (dto.getIsFeatured() != null)
            product.setFeatured(dto.getIsFeatured());
        if (dto.getIsActive() != null)
            product.setActive(dto.getIsActive());
    }
}
