spring.application.name=ecommerce

# ── PostgreSQL ──
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ── JWT ──
jwt.secret=dGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUU2lnbmluZzEyMzQ1Njc4OQ==
jwt.expiration=86400000
